// PalestineList search
//
// Wires up the search icon, modal overlay, keyboard shortcuts, MiniSearch
// keyword index, the "help me decide" recommendation flow (the only place
// we call Thaura), and click-to-jump-and-highlight behavior on the
// destination entry.
//
// External requirements (loaded before this file in index.html):
//   - MiniSearch (window.MiniSearch)
//   - TabManager from main.js (instantiated on DOMContentLoaded)
//
// Data lives at /search-index.json, regenerated by tools/build-search-index.py.
// The AI proxy lives at <WORKER_BASE>/api/recommend and /api/semantic-rank;
// set WORKER_BASE to your deployed Cloudflare Worker URL.

(function () {
    'use strict';

    // ──────────────────────────────────────────────────────────────────
    // Configuration
    // ──────────────────────────────────────────────────────────────────

    // The Cloudflare Worker that proxies Thaura. Leave as the placeholder
    // until you've deployed the worker (see /worker/README.md), then update.
    // If this stays as the placeholder, AI features are gracefully disabled
    // and we fall back to keyword-only search.
    const WORKER_BASE = 'https://search.palestinelist.com';

    // True if the worker URL has been set to something real. We use this
    // to hide / disable the AI bits when the proxy isn't deployed yet.
    const AI_ENABLED = !WORKER_BASE.includes('YOUR-SUBDOMAIN');

    // Where the catalog lives. Built by tools/build-search-index.py.
    const INDEX_URL = 'search-index.json';

    // Max results to display in the keyword list. Anything beyond ~30 just
    // hurts performance and gives the user a "wall of results" feeling.
    const MAX_RESULTS = 30;

    // Max candidates to send to the recommend endpoint. Slightly bigger so
    // the model has room to pick from genres/formats it wouldn't otherwise
    // see if we filtered too aggressively.
    const AI_RECOMMEND_CANDIDATES = 60;

    // Map of catalog `tab` slug → tab-bar data-tab. The catalog already uses
    // the same slugs, but keep this here in case we rename a tab later.
    const TAB_SLUG_TO_DATA_TAB = {
        home: 'home',
        books: 'books',
        'film-video': 'film-video',
        miscellaneous: 'miscellaneous',
        citations: 'citations',
        supplements: 'supplements',
    };

    // Human-friendly tab labels for result meta-rows.
    const TAB_LABELS = {
        home: 'Home',
        books: 'Books',
        'film-video': 'Film & Video',
        miscellaneous: 'Misc.',
        citations: 'Citations',
        supplements: 'Supplements',
    };

    // Format priority for ranking. Lower number = shows up first. Within
    // each bucket, MiniSearch's relevance order is preserved (we rely on
    // Array.prototype.sort being stable in all modern browsers).
    // Anything not in this map — including "podcast" — falls into bucket 5
    // ("everything else"), per the curator's stated ordering.
    const FORMAT_PRIORITY = {
        book: 1,
        film: 2,
        article: 3,
        citation: 4,
        // podcast, other, undefined → 5 (default below)
    };
    const FORMAT_DEFAULT_PRIORITY = 5;

    // ──────────────────────────────────────────────────────────────────
    // State
    // ──────────────────────────────────────────────────────────────────

    let catalog = null;          // { version, entries: [...] }
    let entryById = new Map();   // id → entry, for fast lookups
    let miniIndex = null;        // MiniSearch instance, built lazily
    let loadPromise = null;      // Promise<void> for the catalog fetch

    let activeResults = [];      // currently-visible result entries
    let activeIndex = -1;        // keyboard cursor into activeResults
    let lastQuery = '';          // last issued keyword query (for debouncing)
    let decideAbort = null;      // AbortController for in-flight recommend
    let decideRendered = false;  // has the "help me decide" panel been built?
    let activeFilter = 'all';    // current format filter ('all' | book | film | article | citation | other)

    // ──────────────────────────────────────────────────────────────────
    // DOM references — looked up once on init.
    // ──────────────────────────────────────────────────────────────────

    let els = null;

    function lookupEls() {
        els = {
            toggle: document.getElementById('search-toggle'),
            overlay: document.getElementById('search-overlay'),
            modal: document.querySelector('#search-overlay .search-modal'),
            input: document.getElementById('search-input'),
            close: document.getElementById('search-close'),
            filters: document.getElementById('search-filters'),
            helpButton: document.getElementById('search-help-decide'),
            decide: document.getElementById('search-decide'),
            results: document.getElementById('search-results'),
            empty: document.getElementById('search-empty'),
            credit: document.getElementById('search-credit'),
        };
    }

    // ──────────────────────────────────────────────────────────────────
    // Catalog + MiniSearch setup
    // ──────────────────────────────────────────────────────────────────

    function ensureCatalog() {
        if (catalog) return Promise.resolve(catalog);
        if (loadPromise) return loadPromise;
        // `no-cache` means: don't return a cached copy without checking
        // with the server first. The browser still caches across page
        // loads, but a rebuilt search-index.json will be picked up
        // automatically — no hard-refresh dance required.
        loadPromise = fetch(INDEX_URL, { cache: 'no-cache' })
            .then((r) => {
                if (!r.ok) throw new Error('catalog fetch failed: ' + r.status);
                return r.json();
            })
            .then((data) => {
                catalog = data;
                entryById = new Map(data.entries.map((e) => [e.id, e]));
                buildMiniSearch();
                return catalog;
            })
            .catch((err) => {
                // Reset so a retry on the next open will try again.
                loadPromise = null;
                throw err;
            });
        return loadPromise;
    }

    function buildMiniSearch() {
        if (!window.MiniSearch) {
            console.warn('MiniSearch global missing — keyword search disabled');
            return;
        }
        miniIndex = new MiniSearch({
            idField: 'id',
            // Fields we want to score against. `byline` carries trailing
            // heading text — subtitle and similar — so a full-string query
            // like "<Title> by <Author>" can match. `author` and `year`
            // are first-class so searching "Edward Said" or "2020" finds
            // entries even when those terms aren't in the title.
            fields: ['title', 'author', 'year', 'byline', 'section', 'subsection', 'description'],
            // Fields we want to read back without re-fetching from the catalog.
            // `kind` is included so boostDocument can read it during scoring.
            storeFields: ['title', 'tab', 'subtab', 'section', 'subsection', 'description', 'starred', 'anchor', 'url', 'kind', 'author', 'year'],
            // MiniSearch tokenizes strings — `year` is stored as a number in
            // the catalog, so coerce to string here so it's indexed properly.
            extractField: (doc, field) => {
                const v = doc[field];
                return v == null ? '' : String(v);
            },
            searchOptions: {
                // Author gets the same weight as title so a query like
                // "Edward Said" surfaces books by him, not just books that
                // happen to mention him in the title.
                boost: { title: 3, author: 3, byline: 2.5, subsection: 2, section: 1.5 },
                prefix: true,        // "khal" matches "Khalidi"
                fuzzy: 0.18,         // typo tolerance, ~1 edit in 6 chars
                combineWith: 'AND',  // multi-word queries must all match
            },
        });
        miniIndex.addAll(catalog.entries);
    }

    // True if the user's query suggests they're explicitly looking for a list
    // page (e.g. "reading list", "movie lists"). When false, list-kind entries
    // get demoted in ranking so individual books / films / podcasts surface
    // first. Match whole words to avoid catching "internationalist" etc.
    function userWantsLists(query) {
        return /\b(lists?|reading\s+lists?|book\s+lists?|movie\s+lists?|film\s+lists?)\b/i.test(query);
    }

    // ──────────────────────────────────────────────────────────────────
    // Open / close
    // ──────────────────────────────────────────────────────────────────

    function openSearch() {
        els.overlay.classList.add('visible');
        els.overlay.setAttribute('aria-hidden', 'false');
        document.body.style.overflow = 'hidden';

        // Lazy-load the catalog on first open so we don't pay the cost on
        // every page load. The empty-state copy stays visible until results
        // come in, so there's nothing jarring during the fetch.
        ensureCatalog().catch((err) => {
            console.error(err);
            renderError("Couldn't load the search index. Try refreshing the page.");
        });

        // Focus the input on next frame so the overlay's transition has a
        // chance to begin (otherwise iOS Safari sometimes drops the focus).
        requestAnimationFrame(() => els.input.focus());
    }

    function closeSearch() {
        els.overlay.classList.remove('visible');
        els.overlay.setAttribute('aria-hidden', 'true');
        document.body.style.overflow = '';

        // Abort any in-flight recommendation request so we don't waste
        // tokens on results the user will never see.
        if (decideAbort) decideAbort.abort();

        // Return focus to the search toggle so keyboard users don't lose
        // their place in the page.
        els.toggle.focus();
    }

    function isOpen() {
        return els.overlay.classList.contains('visible');
    }

    // ──────────────────────────────────────────────────────────────────
    // Rendering
    // ──────────────────────────────────────────────────────────────────

    function escapeHtml(s) {
        return String(s == null ? '' : s)
            .replace(/&/g, '&amp;')
            .replace(/</g, '&lt;')
            .replace(/>/g, '&gt;')
            .replace(/"/g, '&quot;')
            .replace(/'/g, '&#39;');
    }

    // Highlight occurrences of any query term in `text`. Used to make matches
    // visible in titles/descriptions without leaning on MiniSearch's match
    // metadata (which is keyed by stem, not the user's literal input).
    function highlight(text, terms) {
        if (!text) return '';
        if (!terms || terms.length === 0) return escapeHtml(text);
        const cleanTerms = terms
            .map((t) => t.trim())
            .filter((t) => t.length >= 2)
            .map((t) => t.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'));
        if (cleanTerms.length === 0) return escapeHtml(text);
        const re = new RegExp('(' + cleanTerms.join('|') + ')', 'gi');
        return escapeHtml(text).replace(re, '<mark>$1</mark>');
    }

    function tabLabel(entry) {
        const base = TAB_LABELS[entry.tab] || entry.tab;
        if (entry.subtab) {
            // Capitalize the subtab slug for display.
            const sub = entry.subtab[0].toUpperCase() + entry.subtab.slice(1);
            return `${base} · ${sub}`;
        }
        return base;
    }

    // Render a list of catalog entries to the results panel. `terms` is the
    // user's split query (used for highlighting). `whyById` is an optional
    // map from entry id → one-line "why this was picked" string used by the
    // recommendation flow.
    function renderResults(entries, terms, whyById) {
        activeResults = entries;
        activeIndex = entries.length > 0 ? 0 : -1;

        if (entries.length === 0) {
            els.results.innerHTML = '';
            els.empty.hidden = false;
            return;
        }
        els.empty.hidden = true;

        const html = entries.map((e, i) => {
            const meta = [
                e.starred ? '<span class="sr-star" aria-label="Featured">⭐</span>' : '',
                `<span>${escapeHtml(tabLabel(e))}</span>`,
                e.section ? `<span class="sr-section">· ${escapeHtml(e.section)}</span>` : '',
            ].filter(Boolean).join(' ');
            // Author + year live on their own line directly under the title.
            // Either or both may be missing — only render the line when we
            // have at least one piece, joined by " · " for visual rhythm.
            const bylineBits = [
                e.author ? highlight(e.author, terms) : '',
                e.year ? highlight(String(e.year), terms) : '',
            ].filter(Boolean);
            const bylineRow = bylineBits.length
                ? `<div class="sr-byline">${bylineBits.join(' · ')}</div>`
                : '';
            const why = whyById && whyById.get(e.id);
            return (
                `<li class="search-result${i === activeIndex ? ' active' : ''}" ` +
                `role="option" data-id="${e.id}" data-index="${i}">` +
                `<div class="sr-title">${highlight(e.title, terms)}</div>` +
                `<div class="sr-meta">${meta}</div>` +
                bylineRow +
                (why
                    ? `<div class="sr-why">${escapeHtml(why)}</div>`
                    : e.description
                        ? `<div class="sr-desc">${highlight(e.description, terms)}</div>`
                        : '') +
                `</li>`
            );
        }).join('');
        els.results.innerHTML = html;
    }

    function renderError(message) {
        els.results.innerHTML = '';
        els.empty.hidden = false;
        els.empty.innerHTML = `<p>${escapeHtml(message)}</p>`;
    }

    // Single place to wipe everything in the results area so stale rows,
    // recommendation notes, and credit text never linger across mode
    // changes. Called whenever we transition between search modes.
    function clearResultsArea() {
        els.results.innerHTML = '';
        document
            .querySelectorAll('.search-decide-note')
            .forEach((el) => el.remove());
        setCredit('');
        activeResults = [];
        activeIndex = -1;
    }

    function setCredit(html) {
        if (els.credit) els.credit.innerHTML = html;
    }

    // ──────────────────────────────────────────────────────────────────
    // Keyword search
    // ──────────────────────────────────────────────────────────────────

    // Does an entry match the active filter? "all" matches everything.
    // "other" matches anything not in the four named buckets (podcast,
    // "other", or missing).
    function matchesActiveFilter(entry) {
        if (activeFilter === 'all') return true;
        if (activeFilter === 'other') {
            return !['book', 'film', 'article', 'citation'].includes(entry.format);
        }
        return entry.format === activeFilter;
    }

    function runKeywordSearch(query) {
        if (!miniIndex || !query.trim()) {
            renderResults([], []);
            return [];
        }
        const wantsLists = userWantsLists(query);
        const hits = miniIndex.search(query, {
            combineWith: 'AND',
            // Per-document boost. List-kind entries get a 0.4x multiplier
            // (a 60% penalty) when the user's query doesn't explicitly
            // mention lists, pushing them below individual works. They
            // still appear in results — just further down — so a user
            // looking for a comprehensive list can scroll to find one.
            boostDocument: (id, term, storedFields) => {
                if (!wantsLists && storedFields && storedFields.kind === 'list') {
                    return 0.4;
                }
                return 1;
            },
        });
        // MiniSearch returns objects with stored fields plus score/match info,
        // already sorted by relevance. We map back to catalog entries (which
        // carry the full description and url), apply the active format
        // filter, then stable-sort by format priority so books surface
        // first, then films, articles, citations, and everything else last.
        // Within each format, MiniSearch's relevance ordering is preserved
        // by .sort()'s stability.
        let entries = hits
            .map((h) => entryById.get(h.id))
            .filter(Boolean)
            .filter(matchesActiveFilter);
        entries.sort(
            (a, b) =>
                (FORMAT_PRIORITY[a.format] || FORMAT_DEFAULT_PRIORITY) -
                (FORMAT_PRIORITY[b.format] || FORMAT_DEFAULT_PRIORITY),
        );
        return entries.slice(0, MAX_RESULTS);
    }

    // The keyword search handler. No AI involvement — that's reserved for
    // the "Help me decide" flow. The credit footer stays cleared here so
    // the modal looks neutral during regular search.
    async function handleQueryChange() {
        const q = els.input.value.trim();
        lastQuery = q;
        if (!q) {
            renderResults([], []);
            setCredit('');
            return;
        }
        await ensureCatalog();
        // Guard against a stale call winning the race: if the user kept
        // typing while ensureCatalog() was loading, only the most recent
        // query gets to render.
        if (lastQuery !== q) return;
        const terms = q.split(/\s+/);
        const baseEntries = runKeywordSearch(q);
        renderResults(baseEntries, terms);
        setCredit('');
    }

    // ──────────────────────────────────────────────────────────────────
    // Compact representation for AI prompts
    // ──────────────────────────────────────────────────────────────────

    function compactForAI(e) {
        // Mirrors worker.js compactCandidate exactly so the model sees a
        // consistent shape regardless of which endpoint we hit.
        const out = { id: e.id, title: e.title, tab: e.tab };
        if (e.subtab) out.subtab = e.subtab;
        if (e.section) out.section = e.section;
        if (e.starred) out.starred = true;
        if (e.description) {
            out.description = e.description.length > 200
                ? e.description.slice(0, 200).replace(/\s\S*$/, '') + '…'
                : e.description;
        }
        return out;
    }

    function thauraCreditHtml() {
        return 'Ranked by <a href="https://thaura.ai" target="_blank" rel="noopener">Thaura</a>';
    }

    // ──────────────────────────────────────────────────────────────────
    // "Help me decide" flow
    // ──────────────────────────────────────────────────────────────────

    function openDecide() {
        if (!els.decide) return;
        // hasChildNodes() returns true even for HTML comments (the placeholder
        // comment inside the empty div counts!), so we track render state
        // with an explicit flag instead.
        if (!decideRendered) {
            els.decide.innerHTML = renderDecidePanel();
            wireDecidePanel();
            decideRendered = true;
        }
        els.decide.hidden = false;
        els.helpButton.classList.add('active');
        // Wipe any previous results/notes/credit so the modal looks like a
        // fresh state when the help panel opens.
        clearResultsArea();
        els.empty.hidden = true;
        // Also wipe stale status text from either mode so a previous
        // session's "Asking Thaura…" doesn't reappear when reopening.
        setDecideStatus('guided', '');
        setDecideStatus('free', '');
        // Focus the first field for keyboard users.
        const firstField = els.decide.querySelector('select, textarea');
        if (firstField) firstField.focus();
    }

    function closeDecide() {
        if (els.decide) els.decide.hidden = true;
        els.helpButton.classList.remove('active');
        if (els.input.value.trim()) {
            handleQueryChange();
        } else {
            renderResults([], []);
        }
    }

    // Markup for the "How does this work?" affordance next to a Recommend
    // button. Returned as a string so we can drop it into both forms with
    // a single source of truth. Each instance gets its own bubble so
    // toggling state is local to one form.
    function infoLinkHtml() {
        return `
            <span class="search-decide-info-wrap">
                <button class="search-decide-info" type="button" aria-expanded="false">How does this work?</button>
                <span class="search-decide-info-bubble" hidden role="tooltip">
                    This recommendation feature is powered by Thaura.ai, the ethical AI companion founded by two Syrian brothers. For more information,
                    <a href="https://thaura.ai/home" target="_blank" rel="noopener">go here</a>.
                </span>
            </span>
        `;
    }

    function renderDecidePanel() {
        return `
            <div class="search-decide-tabs" role="tablist">
                <button class="search-decide-tab" id="decide-tab-guided"
                        role="tab" aria-selected="true" data-mode="guided">Guided</button>
                <button class="search-decide-tab" id="decide-tab-free"
                        role="tab" aria-selected="false" data-mode="free">In your own words</button>
            </div>
            <div class="search-decide-quiz" id="decide-form-guided">
                <div class="search-decide-field">
                    <label for="decide-format">Format</label>
                    <select id="decide-format">
                        <option value="">No preference</option>
                        <option value="book">Book</option>
                        <option value="film or video">Film or video</option>
                        <option value="podcast">Podcast</option>
                        <option value="article">Article</option>
                        <option value="short read or short video">Short read or short video</option>
                    </select>
                </div>
                <div class="search-decide-field">
                    <label for="decide-time">Time available</label>
                    <select id="decide-time">
                        <option value="">No preference</option>
                        <option value="under 30 minutes">Under 30 min</option>
                        <option value="about an hour">About an hour</option>
                        <option value="a long evening (2-3 hours)">A long evening</option>
                        <option value="a multi-day commitment">Multi-day commitment</option>
                    </select>
                </div>
                <div class="search-decide-field">
                    <label for="decide-depth">Depth</label>
                    <select id="decide-depth">
                        <option value="">No preference</option>
                        <option value="brand new to Palestine">New to the topic</option>
                        <option value="have some background">Some background</option>
                        <option value="deep in the subject already">Deep already</option>
                    </select>
                </div>
                <div class="search-decide-field">
                    <label for="decide-mood">Mood / angle</label>
                    <select id="decide-mood">
                        <option value="">No preference</option>
                        <option value="historical context">Historical context</option>
                        <option value="current events and the ongoing genocide">Current events</option>
                        <option value="hopeful / resistance / liberation">Hopeful / resistance</option>
                        <option value="personal stories from Palestinians">Personal stories</option>
                        <option value="critical analysis of Zionism / settler colonialism">Critical analysis</option>
                        <option value="how to get involved / solidarity">How to get involved</option>
                    </select>
                </div>
                <div class="search-decide-actions">
                    <span class="search-decide-status" id="decide-status"></span>
                    ${infoLinkHtml()}
                    <button class="search-decide-go" id="decide-go">
                        <i class="fa-solid fa-sparkles"></i> Recommend
                    </button>
                </div>
            </div>
            <div class="search-decide-freetext" id="decide-form-free" hidden>
                <div class="search-decide-field">
                    <label for="decide-prompt">Tell me what you're looking for</label>
                    <textarea id="decide-prompt" placeholder="e.g. a book by a Palestinian woman about the 1948 expulsion, ideally not too long"></textarea>
                </div>
                <div class="search-decide-actions">
                    <span class="search-decide-status" id="decide-status-free"></span>
                    ${infoLinkHtml()}
                    <button class="search-decide-go" id="decide-go-free">
                        <i class="fa-solid fa-sparkles"></i> Recommend
                    </button>
                </div>
            </div>
        `;
    }

    function wireDecidePanel() {
        const tabGuided = document.getElementById('decide-tab-guided');
        const tabFree = document.getElementById('decide-tab-free');
        const formGuided = document.getElementById('decide-form-guided');
        const formFree = document.getElementById('decide-form-free');

        function setMode(mode) {
            const guided = mode === 'guided';
            tabGuided.setAttribute('aria-selected', guided);
            tabFree.setAttribute('aria-selected', !guided);
            formGuided.hidden = !guided;
            formFree.hidden = guided;
            // Switching tabs wipes any results / notes from the previous
            // mode. The two modes are mutually exclusive — nothing from
            // the form you just left should linger in the results area.
            clearResultsArea();
            // Cancel any in-flight recommendation so its eventual response
            // doesn't render into the new (now-unrelated) mode.
            if (decideAbort) {
                decideAbort.abort();
                decideAbort = null;
            }
            // Also clear any status text on either form so it doesn't
            // carry over (e.g. "No picks came back…" from the other mode).
            setDecideStatus('guided', '');
            setDecideStatus('free', '');
            const focusEl = guided ? formGuided.querySelector('select') : document.getElementById('decide-prompt');
            if (focusEl) focusEl.focus();
        }
        tabGuided.addEventListener('click', () => setMode('guided'));
        tabFree.addEventListener('click', () => setMode('free'));

        document.getElementById('decide-go').addEventListener('click', () => runRecommend('guided'));
        document.getElementById('decide-go-free').addEventListener('click', () => runRecommend('free'));
        document.getElementById('decide-prompt').addEventListener('keydown', (e) => {
            if (e.key === 'Enter' && (e.metaKey || e.ctrlKey)) {
                e.preventDefault();
                runRecommend('free');
            }
        });

        // "How does this work?" tooltip bubbles. Each Recommend button gets
        // its own. Clicking the link toggles its bubble; clicking outside
        // any bubble closes them; Escape closes them without dismissing
        // the whole search overlay.
        els.decide.querySelectorAll('.search-decide-info').forEach((btn) => {
            btn.addEventListener('click', (e) => {
                e.stopPropagation();
                const bubble = btn.parentElement.querySelector(
                    '.search-decide-info-bubble',
                );
                const isOpen = !bubble.hidden;
                closeAllInfoBubbles();
                if (!isOpen) {
                    bubble.hidden = false;
                    btn.setAttribute('aria-expanded', 'true');
                }
            });
        });
        // Clicks anywhere else inside the modal close open bubbles. We
        // attach to the overlay (not document) so this listener doesn't
        // outlive the modal's open state.
        els.overlay.addEventListener('click', (e) => {
            if (!e.target.closest('.search-decide-info-wrap')) {
                closeAllInfoBubbles();
            }
        });
    }

    // Helper: close every "How does this work?" bubble in the modal and
    // reset its trigger's aria-expanded state.
    function closeAllInfoBubbles() {
        document
            .querySelectorAll('.search-decide-info-bubble')
            .forEach((b) => {
                b.hidden = true;
            });
        document
            .querySelectorAll('.search-decide-info')
            .forEach((b) => b.setAttribute('aria-expanded', 'false'));
    }

    async function runRecommend(mode) {
        if (!AI_ENABLED) {
            renderError('AI recommendations need the Cloudflare Worker to be deployed first. See /worker/README.md.');
            return;
        }
        await ensureCatalog();

        let payload;
        let queryForFilter;
        if (mode === 'guided') {
            const answers = {
                format: val('decide-format'),
                time: val('decide-time'),
                depth: val('decide-depth'),
                mood: val('decide-mood'),
            };
            // Drop empty fields so the prompt stays compact.
            Object.keys(answers).forEach((k) => { if (!answers[k]) delete answers[k]; });
            if (Object.keys(answers).length === 0) {
                setDecideStatus('guided', 'Pick at least one option, or use "In your own words".');
                return;
            }
            payload = { answers };
            queryForFilter = [answers.mood, answers.format].filter(Boolean).join(' ');
        } else {
            const q = val('decide-prompt').trim();
            if (!q) {
                setDecideStatus('free', 'Tell me what you\'re looking for first.');
                return;
            }
            payload = { query: q };
            queryForFilter = q;
        }

        // Build the candidate set. Strategy:
        //   - If we have a usable filter query, pre-filter via MiniSearch.
        //   - Otherwise sample broadly (starred first, then a slice across
        //     each tab) so the model has variety to pick from.
        let candidates = [];
        if (queryForFilter && miniIndex) {
            const hits = miniIndex.search(queryForFilter, { combineWith: 'OR' });
            candidates = hits.slice(0, AI_RECOMMEND_CANDIDATES)
                .map((h) => entryById.get(h.id))
                .filter(Boolean);
        }
        if (candidates.length < 12) {
            // Fallback: starred entries first (curator's picks), then fill out
            // with a tab-balanced sample so we don't bias toward one section.
            const stars = catalog.entries.filter((e) => e.starred);
            const seen = new Set(candidates.map((c) => c.id));
            for (const e of stars) {
                if (candidates.length >= AI_RECOMMEND_CANDIDATES) break;
                if (!seen.has(e.id)) { candidates.push(e); seen.add(e.id); }
            }
            // Top up across tabs.
            if (candidates.length < AI_RECOMMEND_CANDIDATES) {
                for (const e of catalog.entries) {
                    if (candidates.length >= AI_RECOMMEND_CANDIDATES) break;
                    if (!seen.has(e.id)) { candidates.push(e); seen.add(e.id); }
                }
            }
        }

        const compact = candidates.map(compactForAI);

        setDecideStatus(mode, 'Asking Thaura for a personalized pick', true);
        if (decideAbort) decideAbort.abort();
        decideAbort = new AbortController();

        // Hard queries (e.g. "a book I can finish in 30 minutes") can make
        // the model take a long time or fail to converge. Without this,
        // the status message just sits there forever. After 8 seconds we
        // soften the wait copy so the user knows it's still working; at
        // 30 seconds we abort and surface a friendly fallback.
        const SOFT_WAIT_MS = 8000;
        const HARD_TIMEOUT_MS = 30000;
        let timedOut = false;
        const softWaitTimer = setTimeout(() => {
            setDecideStatus(mode, "Still searching", true);
        }, SOFT_WAIT_MS);
        const hardTimeoutTimer = setTimeout(() => {
            timedOut = true;
            if (decideAbort) decideAbort.abort();
        }, HARD_TIMEOUT_MS);
        const clearTimers = () => {
            clearTimeout(softWaitTimer);
            clearTimeout(hardTimeoutTimer);
        };

        try {
            const res = await fetch(`${WORKER_BASE}/api/recommend`, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ ...payload, candidates: compact }),
                signal: decideAbort.signal,
            });
            clearTimers();
            // Friendly handling for the known failure modes before falling
            // through to a generic error. Each branch ends the flow so the
            // user gets a single calm message instead of raw worker text.
            if (res.status === 429) {
                setDecideStatus(
                    mode,
                    "Too many requests in a short time. Please wait a moment and try again.",
                );
                return;
            }
            if (res.status >= 500 && res.status < 600) {
                setDecideStatus(
                    mode,
                    "The recommendation service is temporarily unavailable. Keyword search still works in the meantime.",
                );
                return;
            }
            if (!res.ok) {
                const text = await res.text();
                throw new Error(`worker ${res.status}: ${text.slice(0, 200)}`);
            }
            const data = await res.json();
            if (!Array.isArray(data.recommendations) || data.recommendations.length === 0) {
                setDecideStatus(
                    mode,
                    "No matches fit those constraints — try loosening one of the inputs.",
                );
                return;
            }
            const whyById = new Map(data.recommendations.map((r) => [r.id, r.why]));
            const picks = data.recommendations
                .map((r) => entryById.get(r.id))
                .filter(Boolean);
            renderResults(picks, [], whyById);
            setCredit(thauraCreditHtml());
            // Clear the loading status so it doesn't linger as stale text
            // when the user reopens the decide panel later.
            setDecideStatus(mode, '');
            // Close the form so the recommendations get full attention.
            els.decide.hidden = true;
            els.helpButton.classList.remove('active');
            // Surface the note (if any) above the results.
            if (data.note) {
                const noteEl = document.createElement('div');
                noteEl.className = 'search-decide-note';
                noteEl.textContent = data.note;
                els.results.parentNode.insertBefore(noteEl, els.results);
                // Remove on next render so it doesn't stack.
                els.results.addEventListener('click', () => noteEl.remove(), { once: true });
                els.input.addEventListener('input', () => noteEl.remove(), { once: true });
            }
        } catch (err) {
            clearTimers();
            if (err.name === 'AbortError') {
                if (timedOut) {
                    setDecideStatus(
                        mode,
                        "Took too long to find a match — try a less specific request.",
                    );
                }
                // Otherwise the abort was user-initiated (closed modal,
                // switched tabs, etc.) — no message needed.
                return;
            }
            if (err.name === 'TypeError') {
                // fetch() throws TypeError for network failures — offline,
                // DNS issues, CORS rejected before status, etc.
                setDecideStatus(
                    mode,
                    "Couldn't reach the recommendation service. Check your connection and try again.",
                );
                return;
            }
            // Genuine unexpected error — keep the message calm but log
            // detail to the console so you can see what happened.
            console.warn('recommendation failed:', err);
            setDecideStatus(mode, 'Something went wrong. Please try again.');
        }
    }

    function val(id) {
        const el = document.getElementById(id);
        return el ? el.value : '';
    }

    function setDecideStatus(mode, message, loading = false) {
        const id = mode === 'free' ? 'decide-status-free' : 'decide-status';
        const el = document.getElementById(id);
        if (!el) return;
        el.textContent = message;
        // Loading messages get an animated trailing ellipsis via CSS so
        // the user can see the indicator pulse. Error/empty messages
        // don't — they're terminal states.
        el.classList.toggle('is-loading', !!message && loading);
    }

    // ──────────────────────────────────────────────────────────────────
    // Jump-to-entry + highlight on click
    // ──────────────────────────────────────────────────────────────────

    function openEntry(entry) {
        if (!entry) return;
        // The catalog stores the original target URL on every entry. If the
        // user clicks a result, that's what they want — open it in a new tab
        // for external resources, or jump-and-highlight if it's on this site.
        const isInternal =
            entry.url.startsWith('#') ||
            /https?:\/\/(www\.)?palestinelist\.com\//i.test(entry.url);

        if (!isInternal) {
            window.open(entry.url, '_blank', 'noopener,noreferrer');
            return;
        }
        // Fall back to anchor-scroll on the current page.
        closeSearch();
        const dataTab = TAB_SLUG_TO_DATA_TAB[entry.tab] || entry.tab;
        if (window.__tabManager) {
            window.__tabManager.switchTab(dataTab, { subtab: entry.subtab || null });
        }
        if (entry.anchor) {
            // Defer so the tab switch has rendered its content first.
            requestAnimationFrame(() => {
                const target = document.getElementById(entry.anchor);
                if (!target) return;
                target.scrollIntoView({ behavior: 'smooth', block: 'start' });
                target.classList.add('search-jump-highlight');
                setTimeout(() => target.classList.remove('search-jump-highlight'), 1700);
            });
        }
    }

    // ──────────────────────────────────────────────────────────────────
    // Event wiring
    // ──────────────────────────────────────────────────────────────────

    function moveCursor(delta) {
        if (activeResults.length === 0) return;
        activeIndex = (activeIndex + delta + activeResults.length) % activeResults.length;
        const items = els.results.querySelectorAll('.search-result');
        items.forEach((el, i) => {
            el.classList.toggle('active', i === activeIndex);
            if (i === activeIndex) {
                el.scrollIntoView({ block: 'nearest' });
            }
        });
    }

    function attachEvents() {
        // Open / close
        els.toggle.addEventListener('click', openSearch);
        els.close.addEventListener('click', closeSearch);

        // Click the backdrop (outside the modal) to close.
        els.overlay.addEventListener('click', (e) => {
            if (e.target === els.overlay) closeSearch();
        });

        // Global keyboard: Cmd/Ctrl+K to open from anywhere, Esc to close,
        // arrows to move the cursor, Enter to select, /-key as a vim-style
        // open-search shortcut when not focused on an input.
        document.addEventListener('keydown', (e) => {
            const meta = e.metaKey || e.ctrlKey;
            if (meta && (e.key === 'k' || e.key === 'K')) {
                e.preventDefault();
                isOpen() ? closeSearch() : openSearch();
                return;
            }
            if (!isOpen()) {
                // Open with "/" when not typing in another input/textarea.
                if (e.key === '/' && !/^(INPUT|TEXTAREA)$/.test(document.activeElement?.tagName || '')) {
                    e.preventDefault();
                    openSearch();
                }
                return;
            }
            if (e.key === 'Escape') {
                e.preventDefault();
                // If a "How does this work?" bubble is open, close just
                // that — the user probably wasn't trying to dismiss the
                // whole modal. Falling through to closeSearch if no
                // bubble is open.
                const openBubble = document.querySelector(
                    '.search-decide-info-bubble:not([hidden])',
                );
                if (openBubble) {
                    closeAllInfoBubbles();
                } else {
                    closeSearch();
                }
                return;
            }
            if (e.key === 'ArrowDown') {
                e.preventDefault();
                moveCursor(1);
            } else if (e.key === 'ArrowUp') {
                e.preventDefault();
                moveCursor(-1);
            } else if (e.key === 'Enter' && activeIndex >= 0 && document.activeElement === els.input) {
                e.preventDefault();
                openEntry(activeResults[activeIndex]);
            }
        });

        // Live search as the user types.
        let inputTimer = null;
        els.input.addEventListener('input', () => {
            if (inputTimer) clearTimeout(inputTimer);
            inputTimer = setTimeout(handleQueryChange, 80);
        });

        // Result row clicks (event delegation).
        els.results.addEventListener('click', (e) => {
            const row = e.target.closest('.search-result');
            if (!row) return;
            const id = Number(row.dataset.id);
            const entry = entryById.get(id);
            if (entry) openEntry(entry);
        });

        // Format filter chip clicks (event delegation). Updating the
        // filter re-runs the current query — or, if the query is empty,
        // does nothing visible (the empty state stays put). A second
        // click on the active chip is a no-op; clicking a different chip
        // swaps the selection.
        if (els.filters) {
            els.filters.addEventListener('click', (e) => {
                const btn = e.target.closest('.search-filter');
                if (!btn) return;
                const format = btn.dataset.format;
                if (!format || format === activeFilter) return;
                activeFilter = format;
                els.filters.querySelectorAll('.search-filter').forEach((b) => {
                    const isActive = b.dataset.format === activeFilter;
                    b.classList.toggle('active', isActive);
                    b.setAttribute('aria-pressed', isActive ? 'true' : 'false');
                });
                // Re-run the current query so the filter takes effect.
                if (els.input.value.trim()) handleQueryChange();
            });
        }

        // "Help me decide" button.
        els.helpButton.addEventListener('click', () => {
            const isOpenAlready = els.decide && !els.decide.hidden;
            if (isOpenAlready) {
                closeDecide();
            } else {
                openDecide();
            }
        });
    }

    // ──────────────────────────────────────────────────────────────────
    // Bootstrap
    // ──────────────────────────────────────────────────────────────────

    function init() {
        lookupEls();
        if (!els.overlay || !els.toggle) return;

        // Hide the "Help me decide" row if the worker isn't deployed — no
        // sense teasing a feature the user can't trigger. Keyword search
        // still works on its own.
        if (!AI_ENABLED) {
            const helpRow = els.helpButton.closest('.search-help-row');
            if (helpRow) helpRow.style.display = 'none';
        }

        attachEvents();
    }

    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', init);
    } else {
        init();
    }
})();
